# Generated by Django 4.1 on 2022-09-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_role_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_teacher_is_active'),
        ('payments', '0003_parentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_payroll', to='employee.employee')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_payroll', to='teacher.teacher')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
