# Generated by Django 4.1 on 2022-09-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_role_employee_role'),
        ('teacher', '0005_teacher_is_active'),
        ('payments', '0004_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'EMPLOYEE'), ('TEACHER', 'TEACHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_payroll', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_payroll', to='teacher.teacher'),
        ),
    ]
