# Generated by Django 4.1 on 2022-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payroll_date_created_payroll_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentpayment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
