# Generated by Django 4.1 on 2023-08-29 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_teacher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(null=True, verbose_name='BirthDay'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='certificate',
            field=models.CharField(blank=True, choices=[('License', 'License'), ('Master', 'Master'), ('Doctor', 'Doctor')], max_length=100, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary'),
        ),
    ]
