# Generated by Django 4.1 on 2022-08-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_kids_date_created_kids_last_updated_kids_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
