# Generated by Django 4.1 on 2022-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_kids_birthday_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
