# Generated by Django 4.1 on 2022-12-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_kids_transportation_student_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_kids', to='student.parent'),
        ),
    ]
