# Generated by Django 4.1 on 2022-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='attendance_time',
            field=models.TimeField(null=True),
        ),
    ]
