# Generated by Django 4.1 on 2022-08-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0005_employeeattendance_employeeleaveitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeaveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED'), ('DECLINED', 'DECLINED')], max_length=100)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_teachers', to='attendance.studentattendance')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='teacher.teacher')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_teacher_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('UNAPPROVED ABSENT', 'UNAPPROVED ABSENT')], max_length=100)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_teachers', to='attendance.studentattendance')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.teacher')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_teacher_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
