# Generated by Django 4.1 on 2022-08-28 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_subject_n_sessions_subject_price'),
        ('student', '0003_kids_is_active_student_is_active'),
        ('attendance', '0006_teacherleaveitem_teacherattendanceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('n_sessions', models.PositiveIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions', to='group.group')),
                ('kid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kid_sessions', to='student.kids')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_sessions', to='student.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teacher.subject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_counter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
